### ISSUE TITLE
Keep two database instances sync

### ISSUE THREAD

**Issue by sh-soltanpour** [gatewayd-io/proposals#3]
The feature I have in mind is a useful feature when you want to migrate your database database. A reasonable approach when migrating a database on production is to run another instance, make it synced with the existing database, and have a tool in between that can keep these two databases in sync for a desired period without affecting performance considerably.

Afterwards, we can completely migrate to the new database and route all of the traffic to it. 

For start, we can start assuming both instances are PostgreSQL, then it can be extended to different pairs as well.

**Comment by mostafa** [comment]
Hey @sh-soltanpour,

That's a great idea for a plugin (or maybe multiple plugins). Let's investigate the details together, so we can come up with a plan for the plugin. So, as I understood (and correct me if I am wrong), these actions need to happen sequentially:
1. A **new database** should be created.
2. The schema of the **existing database** must be transferred to the new database. Data is copied later.
3. A process should start copying data from the existing database to the new database in the background.
4. After the copy is complete (or maybe while copying - which might need more investigation), we should route traffic to both databases. This means that we only receive a single request from the client to the existing database, but we write to two (or possibly more) separate database instances at once. When both are in sync and new requests are routed to both databases, we'll keep both for a while.
    ```mermaid
    flowchart LR
        Client <--> GatewayD
        GatewayD <--route traffic--> DBE["Existing database"]
        GatewayD <--route traffic--> DBN["New database"]
        DBE --copy schema and data--> DBN
    ```
5. At some point we'll stop sending data to the existing database and switch to the new database. This should (or can) happen seamlessly.
6. The existing database will be decommissioned.

Please review the above steps and expand them as necessary.

**Comment by sh-soltanpour** [comment]
Hi Mostafa, 
Thanks for the detailed answer. That's pretty much what I have in my mind.

Regarding step 4, an advanced approach is to keep databases synced even for the requests that are directly going to the database (not through GatewayD), in that case I think we need to compare WALs and duplicate transactions in the second database.

**Comment by mostafa** [comment]
@sh-soltanpour

That's possible, at least for postgres.

**Comment by sh-soltanpour** [comment]
Sounds good! Do you want me to create a PR for this repository for a proposal?

**Comment by mostafa** [comment]
Go for it!
